### ISSUE TITLE
Can cling handlers take mut ref or ownership of options struct?

### ISSUE THREAD

**Issue by slinkydeveloper** [AhmedSoliman/cling#6]
If no, why?

**Comment by AhmedSoliman** [comment]
This was discussed offline sometime ago, passing mut references means that we must guarantee that handlers are either `'static` or they won't hold any of those references, and they are strictly sequential in execution. Because we assume that the side of the options are small and cheap to copy, the design optimizes for developer convenience and flexibility instead.
